### ISSUE TITLE
Category search

### ISSUE THREAD

**Issue by aleccool213** [asarode/termflix#7]
The npm module used, [tpb](https://www.npmjs.com/package/tpb), has the option for category search. I am assuming it would be sort of easy to implement this as a prompt to the user if a certain flag was inputted. like `termflix search [query] -c`, and then categories would show up. Orrrrrrrrr.... you could have all of the catrgories listed via `termflix --help` and then just go `termflix search [query] -c movies`. Or maybe both.

**Comment by asarode** [comment]
From my understanding, the only categories available are:
- audio
- video (default)
- applications
- games
- porn
- other

So I just limit to searching for videos since it wouldn't make sense to stream other categories.. well maybe the porn category would make sense but I'd rather not enable that. 

Is there a way to make the categories narrower than that?

**Comment by aleccool213** [comment]
Maybe not in the current module you are using. I noticed on npm there were other tpb modules that were applicable to the app so maybe switching is an option.

**Comment by asarode** [comment]
@danyocean sent me a link to this torrent search site: https://getstrike.net/torrents/. They have an npm wrapper too: https://www.npmjs.com/package/strike-api so I think I'm going to change the search to their api. They have better categories too so that should fix this issue.

It should also solve the problem of relying so heavily on The Pirate Bay being up. Right now you can't search anything because The Pirate Bay is down :(

**Comment by asarode** [comment]
Just added the ability to search by category. You can use it by doing `termflix search [query] -c [categories]` The long form of the flag is `--category` and the options are "movies", "tv", and "anime". Those were the only categories that made sense to include. Now you can search Harry Potter by movies and not worry about any books coming up! :tada: 

This should be included in the next release that'll most likely go out tomorrow.

Commit: [add --category option to search](https://github.com/asarode/termflix/commit/cfc716ef9dc4499a935fcfef25447732a6b4c7aa)
